export type ResolverFn = () => string;

import {
  ALLOWED_TOOLS_STANDARD,
  ALLOWED_TOOLS_CHAIN,
  ALLOWED_TOOLS_ORCHESTRATOR,
  ALLOWED_TOOLS_REVIEW,
  ALLOWED_TOOLS_OPS,
  ALLOWED_TOOLS_INTELLIGENCE,
  ALLOWED_TOOLS_DESIGN,
  ALLOWED_TOOLS_RESEARCH,
} from "./tools";
import { DECISION_FORMAT } from "./decision";
import { REACTIVE_METHODOLOGY } from "./methodology";
import { CONFIDENCE_CALIBRATION } from "./confidence";
import { ARTIFACT_READ_PROTOCOL } from "./artifacts";
import { CREDIT_RUNOUT_PROJECTION } from "./credit-runout";

export const RESOLVERS: Record<string, ResolverFn> = {
  ALLOWED_TOOLS_STANDARD,
  ALLOWED_TOOLS_CHAIN,
  ALLOWED_TOOLS_ORCHESTRATOR,
  ALLOWED_TOOLS_REVIEW,
  ALLOWED_TOOLS_OPS,
  ALLOWED_TOOLS_INTELLIGENCE,
  ALLOWED_TOOLS_DESIGN,
  ALLOWED_TOOLS_RESEARCH,
  DECISION_FORMAT,
  REACTIVE_METHODOLOGY,
  CONFIDENCE_CALIBRATION,
  ARTIFACT_READ_PROTOCOL,
  CREDIT_RUNOUT_PROJECTION,
};
